In [1]:
import torch

In [2]:
torch.__version__

'2.0.0+cpu'

In [3]:
import numpy as np

In [4]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr.dtype

dtype('int32')

In [5]:
#Convert Numpy to Pytorch Tensor
tensor = torch.from_numpy(arr)
tensor

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [7]:
#indexing similar to numpy
tensor[2]

tensor(3, dtype=torch.int32)

In [8]:
tensor[1:4]

tensor([2, 3, 4], dtype=torch.int32)

In [ ]:
#Disadvantage of from_numpy. the array and tensor uses the same memory location

In [13]:
tensor[2]=100
tensor[3]=4

In [14]:
tensor

tensor([  1,   2, 100,   4,   5], dtype=torch.int32)

In [ ]:
#prevent this by using torch.tensor

In [15]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  1,   2, 100,   4,   5], dtype=torch.int32)

In [16]:
tensor_arr[3]=50
print(tensor_arr)
print(arr)

tensor([  1,   2, 100,  50,   5], dtype=torch.int32)
[  1   2 100   4   5]


In [19]:
#zeros and ones
torch.zeros(2,3,dtype=torch.float64)


tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(2,3,dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [23]:
#Arithmetic Operation
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [24]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [25]:
c = torch.zeros(3)

In [26]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [27]:
c

tensor([ 7.,  9., 11.])

In [28]:
#Some more operation
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [29]:
torch.add(a,b).sum()

tensor(27.)

In [30]:
#Dot products and multi opertion
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [31]:
x.mul(y)

tensor([12., 20., 30.])

In [32]:
x.dot(y)

tensor(62.)

In [33]:
#matrix multiplication
x = torch.tensor([[1,2,3],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [34]:
torch.matmul(x,y)

tensor([[48., 52.],
        [90., 92.]])

In [35]:
torch.mm(x,y)

tensor([[48., 52.],
        [90., 92.]])

In [36]:
x@y

tensor([[48., 52.],
        [90., 92.]])